version: "3.8" # Specify the version of Docker Compose syntax

services:
  mysql:
    image: mysql:latest # Use the official MySQL image
    container_name: mysql_db # Optional: Name of the container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Password for the MySQL root user
      MYSQL_DATABASE: mydatabase # Name of the database to create
      MYSQL_USER: myuser # Database user
      MYSQL_PASSWORD: mypassword # Password for the database user
    ports:
      - "3306:3306" # Map port 3306 on the host to port 3306 on the container
    volumes:
      - mysql_data:/var/lib/mysql # Persist data between container restarts

volumes:
  mysql_data:
    driver: local # Use the default local driver for volume

